#!/bin/bash

# 从标记段提取网络配置并设置静态 IP（仅修改配置文件，不重启网络）
# 用法：./js2net.sh --config.json
# 注意：需要在 root 环境下运行（不主动检查）

set -e

# 帮助信息
if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
    cat << EOF
用法: $0 --配置文件.json

从配置文件的 ###NETWORK### 段中读取网络配置：
  - address: IP 地址（如 192.168.50.75）
  - netmask: 子网掩码（如 255.255.255.0）
  - gateway: 网关地址（如 192.168.50.1）
  - dns-nameservers: DNS 服务器（可选，如 "192.168.50.1" 或 "8.8.8.8,114.114.114.114"）

脚本将：
  1. 备份原网络配置文件
  2. 修改 /etc/network/interfaces 设置静态 IP
  3. 将配置的 DNS 及中国大陆常用 DNS 写入 /etc/resolv.conf
  4. 不重启网络服务，仅提示用户手动重启或重启系统

注意：为了保持网络稳定，不会自动重启网络，请手动执行重启或重启系统以使配置生效。

示例: $0 --network.json
EOF
    exit 0
fi

# 解析参数：必须使用 --文件名
if [[ $# -ne 1 || ! "$1" =~ ^-- ]]; then
    echo "错误: 必须指定配置文件 (--文件名.json)"
    echo "用法: $0 --config.json"
    exit 1
fi
INPUT_FILE="${1#--}"
if [ ! -f "$INPUT_FILE" ]; then
    echo "错误: 找不到文件 $INPUT_FILE"
    exit 1
fi

# 提取 ###NETWORK### 段
TEMP_CFG=$(mktemp)
sed -n '/###NETWORK###/,/###NETWORK###/p' "$INPUT_FILE" | \
    grep -v '###NETWORK###' | \
    grep -v '^\s*#' | \
    grep -v '^\s*$' > "$TEMP_CFG"

if [ ! -s "$TEMP_CFG" ]; then
    echo "错误: 未找到有效的 ###NETWORK### 配置段"
    rm -f "$TEMP_CFG"
    exit 1
fi

# 解析键值对（支持中文双引号）
declare -A CONFIG
while IFS= read -r line; do
    key=$(echo "$line" | sed -E 's/^[[:space:]]*["“]([^"“”]+)["“”][[:space:]]*:.*$/\1/')
    value=$(echo "$line" | sed -E 's/.*:[[:space:]]*["“]?([^"“”]*?)["“”]?[[:space:]]*,?[[:space:]]*$/\1/')
    if [ -n "$key" ]; then
        CONFIG["$key"]="$value"
    fi
done < "$TEMP_CFG"
rm -f "$TEMP_CFG"

# 获取必需参数
ADDRESS="${CONFIG["address"]}"
NETMASK="${CONFIG["netmask"]}"
GATEWAY="${CONFIG["gateway"]}"
DNS_NAMESERVERS="${CONFIG["dns-nameservers"]}"

if [ -z "$ADDRESS" ] || [ -z "$NETMASK" ] || [ -z "$GATEWAY" ]; then
    echo "错误: 配置中缺少 address、netmask 或 gateway"
    exit 1
fi

echo ">>> 检测到网络配置："
echo "    IP地址: $ADDRESS"
echo "    子网掩码: $NETMASK"
echo "    网关: $GATEWAY"
if [ -n "$DNS_NAMESERVERS" ]; then
    echo "    DNS: $DNS_NAMESERVERS"
else
    echo "    DNS: 未提供，将仅使用默认中国大陆 DNS"
fi

# ==================== 1. 检测网络接口 ====================
ACTIVE_IFACE=$(ip route | grep default | awk '{print $5}' | head -n1)
if [ -z "$ACTIVE_IFACE" ]; then
    ACTIVE_IFACE=$(ip -o link show | awk -F': ' '$2 != "lo" {print $2; exit}')
fi
if [ -z "$ACTIVE_IFACE" ]; then
    echo "错误: 无法检测到活动网络接口"
    exit 1
fi
echo ">>> 检测到活动接口: $ACTIVE_IFACE"

# ==================== 2. 备份并修改 /etc/network/interfaces ====================
INTERFACES_FILE="/etc/network/interfaces"
BACKUP_SUFFIX=".bak_$(date +%Y%m%d_%H%M%S)"
BACKUP_FILE="${INTERFACES_FILE}${BACKUP_SUFFIX}"

if [ -f "$INTERFACES_FILE" ]; then
    cp "$INTERFACES_FILE" "$BACKUP_FILE"
    echo "已备份原网络配置到 $BACKUP_FILE"
fi

# 删除该接口的所有现有配置块
sed -i "/^[[:space:]]*auto $ACTIVE_IFACE\$/,/^$/d" "$INTERFACES_FILE"
sed -i "/^[[:space:]]*allow-hotplug $ACTIVE_IFACE\$/,/^$/d" "$INTERFACES_FILE"
sed -i "/^[[:space:]]*iface $ACTIVE_IFACE /,/^$/d" "$INTERFACES_FILE"

# 追加新的静态 IP 配置
cat >> "$INTERFACES_FILE" <<EOF

# Static IP configured by js2net.sh on $(date)
auto $ACTIVE_IFACE
iface $ACTIVE_IFACE inet static
    address $ADDRESS
    netmask $NETMASK
    gateway $GATEWAY
EOF

if [ -n "$DNS_NAMESERVERS" ]; then
    IFS=',' read -ra DNS_ARRAY <<< "$DNS_NAMESERVERS"
    for dns in "${DNS_ARRAY[@]}"; do
        dns=$(echo "$dns" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
        echo "    dns-nameservers $dns" >> "$INTERFACES_FILE"
    done
fi

echo ">>> 已更新 $INTERFACES_FILE"

# ==================== 3. 不重启网络，仅提示 ====================
echo ""
echo "注意: 为了保持网络稳定，未自动重启网络服务。"
echo "网络配置已修改但尚未生效，请择机手动重启网络或重启系统。"
echo "推荐方式："
echo "  1. 重启系统： reboot"
echo "  2. 或者手动重启网络： systemctl restart networking (可能中断当前连接)"
echo ""

# ==================== 4. 写 DNS 到 /etc/resolv.conf ====================
DEFAULT_DNS=(
    "114.114.114.114"
    "119.29.29.29"
    "223.5.5.5"
)

RESOLV_CONF="/etc/resolv.conf"
if [ -f "$RESOLV_CONF" ]; then
    cp "$RESOLV_CONF" "${RESOLV_CONF}${BACKUP_SUFFIX}"
    echo "已备份原 $RESOLV_CONF 到 ${RESOLV_CONF}${BACKUP_SUFFIX}"
fi

if [ -L "$RESOLV_CONF" ]; then
    echo "警告: $RESOLV_CONF 是符号链接，将直接写入链接指向的真实文件"
    RESOLV_TARGET=$(readlink -f "$RESOLV_CONF")
    if [ -z "$RESOLV_TARGET" ]; then
        echo "错误: 无法获取符号链接的目标"
        exit 1
    fi
else
    RESOLV_TARGET="$RESOLV_CONF"
fi

{
    echo "# Generated by js2net.sh on $(date)"
    echo "# Static DNS configuration"
    if [ -n "$DNS_NAMESERVERS" ]; then
        IFS=',' read -ra DNS_FROM_CONFIG <<< "$DNS_NAMESERVERS"
        for dns in "${DNS_FROM_CONFIG[@]}"; do
            dns=$(echo "$dns" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
            echo "nameserver $dns"
        done
    fi
    for dns in "${DEFAULT_DNS[@]}"; do
        echo "nameserver $dns"
    done
} > "$RESOLV_TARGET"

echo ">>> DNS 配置已写入 $RESOLV_TARGET"

# 如果 systemd-resolved 正在运行，不重启（仅提示）
if systemctl is-active systemd-resolved >/dev/null 2>&1; then
    echo "提示: 检测到 systemd-resolved 正在运行，新的 DNS 配置将在网络重启后生效。"
fi

# ==================== 5. 完成总结 ====================
echo ""
echo "=========================================="
echo "静态 IP 配置已写入（尚未生效）"
echo "  接口: $ACTIVE_IFACE"
echo "  IP: $ADDRESS"
echo "  掩码: $NETMASK"
echo "  网关: $GATEWAY"
echo "  DNS: $(cat "$RESOLV_TARGET" | grep nameserver | awk '{print $2}' | tr '\n' ' ')"
echo ""
echo "原网络配置备份: $BACKUP_FILE"
echo "请重启系统或手动重启网络以使配置生效。"
echo "=========================================="
